name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Test
      run: |
        cd ./src/Pipeline.Tests/
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults
    - name: Coverage Report
      run: |
        reportgenerator -reports:./TestResults/coverage.cobertura.xml -targetdir:CoverageReport -reporttypes:Html
    - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './CoverageReport'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1